import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/theme";

export const profileStyles = StyleSheet.create({
  imageSection: {
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fffbe6",
  },
  imageWrapper: {
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  image: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: COLORS.primary,
    backgroundColor: COLORS.background,
    marginBottom: 15,
  },
  editIcon: {
    position: "absolute",
    bottom: 5,
    right: 5,
    backgroundColor: COLORS.primary,
    padding: 8,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  detailRow: {
    backgroundColor: "#f7f3d5",
    flexDirection: "row",
    marginVertical: 4,
    justifyContent: "space-between",
    width: "100%",
    borderWidth: 1,
    borderColor: "#fce3b1",
    borderRadius: 10,
    padding: 10,
  },
  label: {
    color: COLORS.infodark,
    fontWeight: "bold",
    marginRight: 10,
    fontSize: 20,
  },
  detailText: {
    fontSize: 16,
    color: "#000",
    textAlign: "right",
    width: "80%",
  },
  buttonContainer: {
    marginTop: 10,
    alignItems: "center",
    width: "100%",
  },
  updateButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 30,
    marginBottom: 15,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
  },
  updateButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  contactSection: {
    paddingHorizontal: 20,
    borderColor: COLORS.grey,
    borderWidth: 0.5,
    margin: 10,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 4,
    backgroundColor: "#fceded",
  },
  contactHeading: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 10,
    paddingVertical: 10,
    color: COLORS.infodark,
    borderBottomColor: COLORS.grey,
    borderBottomWidth: 0.3,
  },
  contactOption: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 7,
  },
  contactText: {
    fontSize: 16,
    color: COLORS.text,
    marginLeft: 12,
  },
  logoutButton: {
    backgroundColor: COLORS.danger,
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 15,
    marginBottom: 15,
    shadowColor: COLORS.danger,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 6,
  },
  logoutText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#fffbe6",
    alignItems: "center",
  },
  loadingBox: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 15,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContainer: {
    backgroundColor: "#fffbe6",
    padding: 25,
    borderRadius: 15,
    width: 320,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 8,
  },
  inputField: {
    borderBottomWidth: 1.5,
    borderBottomColor: COLORS.border,
    backgroundColor: "#fffbe6",
    padding: 12,
    marginBottom: 18,
    fontSize: 16,
    color: COLORS.text,
    fontFamily: "Roboto",
  },
  categoryTitle: {
    fontWeight: "bold",
    fontSize: 18,
    color: COLORS.primary,
    // 😬 this can break:
    title: "Best Seller", // <--- invalid style key/value
  },
});
